var GAME = GAME || {};
var renderer,stage,scroller;
var showBall = false;
var showBird = false;

GAME.width = 640;
GAME.height = window.innerHeight * 640 / window.innerWidth;
GAME.ratio = 640 / window.innerWidth;

// 三条时间线
GAME.line = {
    lineA:0,
    lineB:0,
    lineC:0,
    lineFinal:0
}

// GAME - 配置选项
GAME.config = {
    common:[
        "./src/img/sceneA/action1.png",
        "./src/img/sceneA/action2.png",
        "./src/img/sceneA/action3.png",
        "./src/img/sceneA/action4.png",
        "./src/img/sceneA/action5.png",
        "./src/img/sceneA/action6.png",
        "./src/img/sceneA/ball.png",
        "./src/img/sceneA/bigplanet.png",
        "./src/img/sceneA/bird.png",
        "./src/img/sceneA/boom.png",
        "./src/img/sceneA/comet.png",
        "./src/img/sceneA/dotline.png",
        "./src/img/sceneA/earth.png",
        "./src/img/sceneA/finger.png",
        "./src/img/sceneA/hand.png",
        "./src/img/sceneA/light.png",
        "./src/img/sceneA/light2.png",
        "./src/img/sceneA/lingling.png",
        "./src/img/sceneA/loader-inner.png",
        "./src/img/sceneA/loader-text.png",
        "./src/img/sceneA/loader.png",
        "./src/img/sceneA/mouth1.png",
        "./src/img/sceneA/mouth2.png",
        "./src/img/sceneA/paopao.png",
        "./src/img/sceneA/person1.png",
        "./src/img/sceneA/person2.png",
        "./src/img/sceneA/phone.png",
        "./src/img/sceneA/planet1.png",
        "./src/img/sceneA/planet2.png",
        "./src/img/sceneA/planet_top.png",
        "./src/img/sceneA/scene1.jpg",
        "./src/img/sceneA/small-star1.png",
        "./src/img/sceneA/small-star2.png",
        "./src/img/sceneA/starmap1.png",
        "./src/img/sceneA/starmap2.png",
        "./src/img/sceneA/starmap3.png",
        "./src/img/sceneA/tel.png",
        "./src/img/sceneA/text1.png",
        "./src/img/sceneA/text2.png",
        "./src/img/sceneA/text3_1.png",
        "./src/img/sceneA/text3_2.png",
        "./src/img/sceneA/text3_3.png",
        "./src/img/sceneA/text4.png",
        "./src/img/sceneA/text5.png",
        "./src/img/sceneA/tracer.png",
        "./src/img/sceneB/arrow.png",
        "./src/img/sceneB/b1.png",
        "./src/img/sceneB/b2.png",
        "./src/img/sceneB/b3.png",
        "./src/img/sceneB/bg.jpg",
        "./src/img/sceneB/bg2.jpg",
        "./src/img/sceneB/head.png",
        "./src/img/sceneB/length.png",
        "./src/img/sceneB/line.png",
        "./src/img/sceneB/nl.png",
        "./src/img/sceneB/nl_text.png",
        "./src/img/sceneB/paopao.png",
        "./src/img/sceneB/planet_bottom.png",
        "./src/img/sceneB/planet_top.png",
        "./src/img/sceneB/report.jpg",
        "./src/img/sceneB/report2.png",
        "./src/img/sceneB/text1.png",
        "./src/img/sceneB/text1_1.png",
        "./src/img/sceneB/text1_2.png",
        "./src/img/sceneB/text1_3.png",
        "./src/img/sceneB/text2.png",
        "./src/img/sceneB/text2_1.png",
        "./src/img/sceneB/text2_2.png",
        "./src/img/sceneB/text2_3.png",
        "./src/img/sceneB/zn.png",
        "./src/img/sceneB/zn_text.png",
        "./src/img/sceneC/bg.jpg",
        "./src/img/sceneC/bigs.jpg",
        "./src/img/sceneC/final.png",
        "./src/img/sceneC/img1.jpg",
        "./src/img/sceneC/img2.jpg",
        "./src/img/sceneC/light.png",
        "./src/img/sceneC/logo.jpg",
        "./src/img/sceneC/logo.png",
        "./src/img/sceneC/phone.png",
        "./src/img/sceneC/s.png",
        "./src/img/sceneC/smalls.jpg",
        "./src/img/sceneC/text1.png",
        "./src/img/sceneC/text2.png",
        "./src/img/sceneC/text3.png",
        "./src/img/sceneC/text4.png",
        "./src/img/sceneFinal/b1.png",
        "./src/img/sceneFinal/b2.png",
        "./src/img/sceneFinal/b4.png",
        "./src/img/sceneFinal/b5.png",
        "./src/img/sceneFinal/b6.png",
        "./src/img/sceneFinal/b7.png",
        "./src/img/sceneFinal/ball.png",
        "./src/img/sceneFinal/bg.jpg",
        "./src/img/sceneFinal/boy.png",
        "./src/img/sceneFinal/bridge.png",
        "./src/img/sceneFinal/girl.png",
        "./src/img/sceneFinal/happy.png",
        "./src/img/sceneFinal/heart.png",
        "./src/img/sceneFinal/jin.png",
        "./src/img/sceneFinal/love.png",
        "./src/img/sceneFinal/meet.png",
        "./src/img/sceneFinal/nl.png",
        "./src/img/sceneFinal/phone.png",
        "./src/img/sceneFinal/zn.png",
    ],
}

GAME.locationList = [
    {prev:-1,next:1,target:'lineA',start:0,end:(-5897+1136)},
    {prev:0,next:-1,target:'lineB',start:0,end:-2197-640},
    {prev:1,next:-1,target:'lineC',start:0,end:(-1478+GAME.height)},
]